name: Hello Github Action 

# push 했을 때 이벤트가 일어남
on: [push]

jobs: 
    build : 
        runs-on: ubuntu-latest # 어디서 구동할지, 우분투 버전 명시 가능(여기서, 최근 버전으로 사용)
        steps:
            # run 뒤에는 실제 작동하는 코드 넣어야 함
            - name: Hello World 출력!!
              run: echo Hello World
            - name: 디렉토리 출력!!
              run: ls -al
            - name: 파이썬 버전 출력!!
              run: python -V
            # python 파일 실행
            - uses: actions/checkout@v3
            - name: 파이썬 실행!!
              run: python test.py
